### ISSUE TITLE
Encountering Exception

### ISSUE THREAD

**Issue by pharry22** [Microsoft/serilog-sinks-testcorrelator#44]
Hi,
Using your sample code of :

using (TestCorrelator.CreateContext())
{
    Log.Information("My log message!");

    TestCorrelator.GetLogEventsFromCurrentContext()
        .Should().ContainSingle()
        .Which.MessageTemplate.Text
        .Should().Be("My log message!");
}

I get the following exception when running the test in mstest.

An exception occurred while invoking executor 'executor://mstestadapter/v1': Type 'System.Collections.Immutable.ImmutableList`1' in assembly 'System.Collections.Immutable, Version=1.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable.
TelemetryTimeTakenInSecByAdaptersToRunTests

I am using VS 2015 update 3.

**Comment by MitchBodmer** [comment]
Looks like this is an issue with [immutable collections not being serializable in .net core](https://github.com/dotnet/corefx/issues/1272). I'll try to get a fix out soon. Thanks for letting me know!

**Comment by MitchBodmer** [comment]
Just released a new version [3.0.2](https://github.com/Microsoft/serilog-sinks-testcorrelator/pull/45) that should fix this.

**Comment by pharry22** [comment]
Thanks Mitch for the quick response. 3.0.2 fixed my problem but it is not yet in NuGet, I don't know if that is under your control.

**Comment by MitchBodmer** [comment]
Yeah I noticed that. Unfortunately it's not under my control. The publish worked, but the package has been in "validation" for over three hours now! I've contacted Nuget.org support.

**Comment by MitchBodmer** [comment]
It's up now.
