### ISSUE TITLE
Preserve ordering of LogEvents.

### ISSUE THREAD

**Issue by projektsdb** [Microsoft/serilog-sinks-testcorrelator#47]
We need to get log events in the same order as they were written, but TestCorrelator.GetLogEventsFromCurrentContex result is randomly ordered (all timestamp values are the same).

**Comment by MitchBodmer** [comment]
Hey @projektsdb. Check [this ](https://ci.appveyor.com/project/SerilogUtilitiesConcurrentCorrelatorSA/serilog-utilities-concurrent-correlator/build/3.0.3+preserve-ordering-99/artifacts) preview version out and see if it works for you. If it does I'll complete [this PR](https://github.com/Microsoft/serilog-sinks-testcorrelator/pull/48) and publish the Nuget package.

**Comment by projektsdb** [comment]
The system cannot find the file specified.":"System.ValueTuple.
There is some version mismatch. Not sure why.

**Comment by MitchBodmer** [comment]
How are you installing the preview version?

**Comment by MitchBodmer** [comment]
Try this:
 copying the preview version of the Nuget package to a local directory on your machine,and then installing i

**Comment by MitchBodmer** [comment]
@projektsdb have you had a chance to try?

**Comment by projektsdb** [comment]
When I install it as nucket pagacke into my project, it throws System.ValueTuple when I run project.

**Comment by MitchBodmer** [comment]
[This bug](https://github.com/dotnet/standard/issues/476) might be the cause here. In any case, I've removed the reference to System.ValueTuple in [this preview version](https://ci.appveyor.com/project/SerilogUtilitiesConcurrentCorrelatorSA/serilog-utilities-concurrent-correlator/build/3.0.3+preserve-ordering-100/artifacts). Give it a shot.

**Comment by projektsdb** [comment]
This works well. After some testing it seems that ordering also is correct.

**Comment by MitchBodmer** [comment]
Great! I've completed the PR and it should show up in the package feed soon.
